# Generated by Django 5.2.12 on 2026-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lng',
        ),
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, null=True, verbose_name='Id места'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
