# Generated by Django 5.2.12 on 2026-03-22 10:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_lon_place_lng_place_place_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='places/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id места'),
        ),
    ]
