# Generated by Django 5.2 on 2025-07-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_place_id_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lon',
            new_name='lng',
        ),
    ]
