# Generated by Django 5.2 on 2025-07-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
